// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/data.jsondata;
import ballerina/http;
import ballerina/url;

# Mock payment gateway. Collects payments from customers via web and mobile checkout, and pays merchant balances out to their bank accounts. No money moves.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config =  {}, string serviceUrl = "http://localhost:8080/v1") returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # List payments.
    #
    # + headers - Headers to be sent with the request 
    # + return - Ok 
    resource isolated function get payments(map<string|string[]> headers = {}) returns PaymentPage|error {
        string resourcePath = string `/payments`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Authorise a payment.
    #
    # + headers - Headers to be sent with the request 
    # + payload - Payment to authorise 
    # + return - Created 
    resource isolated function post payments(CreatePaymentRequest payload, map<string|string[]> headers = {}) returns Payment|error {
        string resourcePath = string `/payments`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Look up a single payment.
    #
    # + paymentId - Identifier returned when the payment was created
    # + headers - Headers to be sent with the request 
    # + return - Ok 
    resource isolated function get payments/[string paymentId](map<string|string[]> headers = {}) returns Payment|error {
        string resourcePath = string `/payments/${getEncodedUri(paymentId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # List payouts.
    #
    # + headers - Headers to be sent with the request 
    # + return - Ok 
    resource isolated function get payouts(map<string|string[]> headers = {}) returns PayoutPage|error {
        string resourcePath = string `/payouts`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Pay a merchant's balance out to its bank account.
    #
    # + headers - Headers to be sent with the request 
    # + payload - Payout to make 
    # + return - Created 
    resource isolated function post payouts(CreatePayoutRequest payload, map<string|string[]> headers = {}) returns Payout|error {
        string resourcePath = string `/payouts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Look up a single payout.
    #
    # + payoutId - Identifier returned when the payout was created
    # + headers - Headers to be sent with the request 
    # + return - Ok 
    resource isolated function get payouts/[string payoutId](map<string|string[]> headers = {}) returns Payout|error {
        string resourcePath = string `/payouts/${getEncodedUri(payoutId)}`;
        return self.clientEp->get(resourcePath, headers);
    }
}

# Get Encoded URI for a given value.
#
# + value - Value to be encoded
# + return - Encoded string
isolated function getEncodedUri(anydata value) returns string {
    string|error encoded = url:encode(value.toString(), "UTF8");
    if encoded is string {
        return encoded;
    } else {
        return value.toString();
    }
}

# Request to pay a merchant's balance out to its bank account.
public type CreatePayoutRequest record {|
    string merchantId;
    int amount;
    string currency;
    # Bank account a payout is sent to.
    BankAccount bankAccount;
    string reference?;
|};

# An authorised payment.
public type Payment record {|
    string paymentId;
    string merchantId;
    int amount;
    string currency;
    # Channel the payment was initiated from.
    Channel channel;
    # Outcome of a payment authorisation.
    PaymentStatus status;
    string reference?;
    string createdAt;
    string redirectUrl?;
    string deepLink?;
|};

# A page of payments.
public type PaymentPage record {|
    Payment[] items;
    int total;
|};

# Outcome of a payout to a merchant's bank account. A payout settles or fails;
# it is never "authorized", so it carries its own states rather than reusing
# PaymentStatus.
public type PayoutStatus "pending"|"failed"|"paid";

# A payout to a merchant's bank account.
public type Payout record {|
    string payoutId;
    string merchantId;
    int amount;
    string currency;
    # Bank account a payout is sent to.
    BankAccount bankAccount;
    # Outcome of a payout to a merchant's bank account. A payout settles or fails;
    # it is never "authorized", so it carries its own states rather than reusing
    # PaymentStatus.
    PayoutStatus status;
    string reference?;
    string createdAt;
    string failureReason?;
|};

# Channel the payment was initiated from.
public type Channel "mobile"|"web";

# A page of payouts.
public type PayoutPage record {|
    Payout[] items;
    int total;
|};

# Request to authorise a payment.
public type CreatePaymentRequest record {|
    string merchantId;
    int amount;
    string currency;
    # Channel the payment was initiated from.
    Channel channel;
    string reference?;
|};

# Bank account a payout is sent to.
public type BankAccount record {|
    string accountNumber;
    string bankCode;
|};

# Outcome of a payment authorisation.
public type PaymentStatus "pending"|"declined"|"authorized";

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
