// GENERATED by scripts/gen-authz.mjs from specs/design/security.json.
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after the design changes. COMMIT this file: the
// per-component image build cannot see the specs tree.

export type Scope =
  | "disputes:read-all"
  | "disputes:resolve"
  | "merchants:read"
  | "merchants:read-all"
  | "merchants:review"
  | "merchants:suspend"
  | "merchants:update"
  | "payment-links:create"
  | "payment-links:read"
  | "payouts:read"
  | "payouts:request"
  | "transactions:read"
  | "transactions:read-all";

export type Role =
  | "Merchant"
  | "PlatformAdmin";

/** Every handle the catalog declares, sorted. */
export const SCOPES: readonly Scope[] = ["disputes:read-all", "disputes:resolve", "merchants:read", "merchants:read-all", "merchants:review", "merchants:suspend", "merchants:update", "payment-links:create", "payment-links:read", "payouts:read", "payouts:request", "transactions:read", "transactions:read-all"];

/** Every role a person can hold, sorted. Service-kind roles are not here. */
export const ROLES: readonly Role[] = ["Merchant", "PlatformAdmin"];

/** What each role grants. heldRoles() projects the caller's scopes through this. */
export const ROLE_GRANTS: Record<Role, readonly Scope[]> = {
  "Merchant": ["merchants:read", "merchants:update", "payment-links:create", "payment-links:read", "payouts:read", "payouts:request", "transactions:read"],
  "PlatformAdmin": ["disputes:read-all", "disputes:resolve", "merchants:read-all", "merchants:review", "merchants:suspend", "transactions:read-all"],
};

/** The directory groups a role is assigned to — what NoAccess tells a user to ask for. */
export const ROLE_ASSIGN_TO: Record<Role, readonly string[]> = {
  "Merchant": ["Merchants"],
  "PlatformAdmin": ["PlatformAdmins"],
};

/** The roles that can hand this one out — who NoAccess tells a user to ask. */
export const ROLE_ASSIGNABLE_BY: Record<Role, readonly string[]> = {
  "Merchant": [],
  "PlatformAdmin": [],
};

export function isScope(value: string): value is Scope {
  return (SCOPES as readonly string[]).includes(value);
}
