// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "GET /disputes"
  | "GET /health"
  | "GET /me/merchant"
  | "GET /me/payment-links"
  | "GET /me/payouts"
  | "GET /me/transactions"
  | "GET /merchants"
  | "GET /merchants/{merchantId}"
  | "GET /payment-links/{linkId}"
  | "GET /transactions"
  | "POST /disputes/{disputeId}/resolve"
  | "POST /me/merchant"
  | "POST /me/payment-links"
  | "POST /me/payouts"
  | "POST /merchants/{merchantId}/review"
  | "POST /merchants/{merchantId}/suspend"
  | "POST /payment-links/{linkId}/pay"
  | "PUT /me/merchant";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "GET /disputes": { kind: "scope", scope: "disputes:read-all" },
  "GET /health": { kind: "public" },
  "GET /me/merchant": { kind: "scope", scope: "merchants:read" },
  "GET /me/payment-links": { kind: "scope", scope: "payment-links:read" },
  "GET /me/payouts": { kind: "scope", scope: "payouts:read" },
  "GET /me/transactions": { kind: "scope", scope: "transactions:read" },
  "GET /merchants": { kind: "scope", scope: "merchants:read-all" },
  "GET /merchants/{merchantId}": { kind: "scope", scope: "merchants:read-all" },
  "GET /payment-links/{linkId}": { kind: "public" },
  "GET /transactions": { kind: "scope", scope: "transactions:read-all" },
  "POST /disputes/{disputeId}/resolve": { kind: "scope", scope: "disputes:resolve" },
  "POST /me/merchant": { kind: "signedIn" },
  "POST /me/payment-links": { kind: "scope", scope: "payment-links:create" },
  "POST /me/payouts": { kind: "scope", scope: "payouts:request" },
  "POST /merchants/{merchantId}/review": { kind: "scope", scope: "merchants:review" },
  "POST /merchants/{merchantId}/suspend": { kind: "scope", scope: "merchants:suspend" },
  "POST /payment-links/{linkId}/pay": { kind: "public" },
  "PUT /me/merchant": { kind: "scope", scope: "merchants:update" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
